name: Generate Snake Animation

on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write  # ✅ Permissão para fazer push
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # ✅ Histórico completo

      - name: Generate Snake Game
        uses: Platane/snk@v3
        with:
          github_user_name: Deividesouza
          outputs: |
            ./output/github-contribution-grid-snake.svg

      - name: Commit and push changes
        uses: EndBug/add-and-commit@v9
        with:
          author_name: github-actions
          author_email: github-actions@github.com
          message: "generated snake animation"
          add: "output/github-contribution-grid-snake.svg"
          pull: true   # ✅ Garante que irá puxar antes de tentar dar push
          push: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
